### PR TITLE
feat: update book/deploy page

### LINKED ISSUE #240: Explain that contracts return excessive funds upon deployment
And that it's done automatically.

Also, mention that receivers don't do that by default — in order to do refunds in receivers one has to use, say, `self.notify("Cashback".asComment());` or alike by the end of their body.

### LINKED ISSUE #290: Add Blueprint's deployment to book/deploy
As of now, it only features `@tact-lang/deployer`. We should either augment or override current description with Blueprint's approach to deployment and related auto-generated scripts for each contract.

### LINKED ISSUE #889: Explain that contracts return excessive funds upon deployment with `Deployable` trait
And that it's done automatically when the contract uses the `Deployable` trait.

Also, mention that receivers don't do that by default — in order to do refunds in receivers one has to use, say, `self.notify("Cashback".asComment());` or alike by the end of their body.

P.S.: Without inheriting the `Deployable` trait, the contract can still handle the `Deploy` message like so:

```tact
import "@stdlib/deploy"; // to populate ctx and have Deploy msg in sight

contract Example {
    receive(msg: Deploy) {} // no-op, won't return the funds now
}
```

### LINKED ISSUE #890: Add Blueprint's deployment to book/deploy and enhance the page
As of now, it only features `@tact-lang/deployer`. We should either augment or override current description with Blueprint's approach to deployment and related auto-generated scripts for each contract.

1. onchain
2. offchain (external msg to the wallet to initiate this)
3. initial state (code and data) |- address
4. etc.

### PR DESCRIPTION
**Pull request by novusnota**
WIP

Closes tact-lang/tact#889 (Already)
Closes tact-lang/tact#890 (WIP

### CODE REVIEW

**Comment by anton-trunov** [comment]
Any progress here?

**Comment by anton-trunov** [comment]
Any progress here?

**Comment by anton-trunov** [comment]
Any progress here?

**Comment by novusnota** [comment]
Closed in favor of opening a new PR in https://github.com/tact-lang/tact

The commits here should be kept for a while, so the branch must not be deleted!

**Pull request closed without merging**
