### PR TITLE
Refine grammar and style in the documentation's evolution section.

### PR DESCRIPTION
**Pull request by DanIsNearby**

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
Awesome work, thanks so much!

**Comment by DanIsNearby** [comment]
Hi @anton-trunov how do i claim this? 

https://society.ton.org/contribute-to-tact-compiler

**Comment by anton-trunov** [comment]
Hi @DanIsNearby, if you provide your TON wallet address we will do the rest :)

**Comment by DanIsNearby** [comment]
> Hi @DanIsNearby, if you provide your TON wallet address we will do the rest :)

Hello thank you 

UQDKgn16eaCwPci2Xl6mETVSxXtKc8Bi5I09iaAQOAtjs_RW

**Pull request merged**
