### PR TITLE
Fix ton core import in /pages/book/guides/getting-started/deploy.mdx

### LINKED ISSUE #171: Error in code snippet in pages/book/guides/getting-started/deploy.mdx
Hello!

There is error in code snippet (pages/book/guides/getting-started/deploy.mdx) at line 3:
import { Address, beginCell, storeStateInit, contractAddress, toNano } from 'ton-core';

There must be:
import { Address, beginCell, storeStateInit, contractAddress, toNano } from '@ton/core';

### PR DESCRIPTION
**Pull request by koodl**
See https://github.com/tact-lang/tact-docs/issues/171

Fix #171

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
Thanks @koodl! If you share your TON wallet address, I'll arrange the SBT for you

**Comment by koodl** [comment]
> Thanks @koodl! If you share your TON wallet address, I'll arrange the SBT for you

UQCv_g6U-fhIbRTbbJbcUEzjK93ZtXyYAHW46TLb3ZEuY3Qg

**Comment by anton-trunov** [comment]
@koodl Done!

**Comment by koodl** [comment]
> @koodl Done!

Thank you!

**Comment by anton-trunov** [comment]
You are most welcome!

**Pull request merged**
