### PR TITLE
feat: New structure (and much more!)

### LINKED ISSUE #77: tact-doc's changelog is out of sync with tact-lang/tact's changelog
Currently https://docs.tact-lang.org/language/guides/changelog is out of sync with https://github.com/tact-lang/tact/blob/main/CHANGELOG.md.

I think we should stop maintaining the changelog in the Tact docs and just link it from the compiler's repo.

### LINKED ISSUE #79: Proposal: A new structure of the documentation
# Core ideas
1. Documentation should start being helpful as quick as possible (A brief "Getting Started" should be the part of the main/index page)
2. Documentation should differ between advanced and novice users of Tact and TON Blockchain (as mentioned in #54):

### Language/Guides section is getting too big to not have it's own dedicated section

Moreover, its scope is wider than the language itself, as it includes interaction with Tact's tooling and TON Blockchain concepts applied with respect to FunC's idioms and their compatibility with Tact.

Besides, the current naming is more of a misnomer, as it usually means deep articles describing how to make a specific project, while the current ones are more descriptive of the language and, only partly, of it's applications in real-life contracts. This is similar to online documentations other languages have, where they call them Books of the language (See [Rust's documentation book](https://doc.rust-lang.org/book/)). I suppose it would be nice to call our section Book as well. Alternatively, it can be named "Learn".

It's only natural to put #66 there :)

P.S.: All the actual guides and tutorials from people all around TON Blockchain would be referenced in the Ecosystem section covered below.
 
### Getting Started is too slow (`/start`)

People, first coming to the docs should see:
1. Basic overview of it's parts
2. Very brief and very quick "Getting Started" page, telling them how to deploy their first contract and where to look for further information after this. The page shall not go into details and describe, say, receivers like the current `/start` does.

And instead, currently people see some mediocre looking README-like page. Yes, it has some of the important links, but the rest isn't suited for the awesome Tact documentation I'd like to see :)

Information from the current "Getting Started" page should be moved into relevant sections of a new Book section described above.

### Current grammar page is useless (`/language/guides/grammar`)

#76

### Evolution section's scope is too narrow (`/evolution`)

And despite that, it still occupies the whole section of the docs! On top of that, the current changelog page (`/language/guides/changelog`) is out of date and doesn't keep up with latest Tact updates as described in #77.

### Tools section's scope is too narrow (`/tools`)

Instead, it should become a part of a much broader section, Ecosystem, which would cover "what's out there" with more detail than just quick links. This would include the current Tools section and make many detailed references to great content posted to [tact-lang/awesome-tact](https://github.com/tact-lang/awesome-tact).

### Broad ideas

Main page of the docs should have a quick overview of available things and a very short getting started guide for deploying the very first contract as quick as possible.

Three sections, each having an [index page describing available contents](https://nextra.site/docs/docs-theme/page-configuration#folders-with-index-page). Their position indicates the levels of immersion into Tact and TON Blockchain, going from the very shallow on the "left" (main page) to the very deep and very broad on the "right" (ecosystem section):
1. Book (or Learn) — intended for those having surface-level (or no) knowledge of Tact and TON, or for those familiar with other blockchains (#54, #67).
2. Language — for people wanting to go deeper, and those (already) familiar with TON. More of a detailed reference, then a manual.
3. Ecosystem — for people wanting to go broader and, perhaps, contribute to the ecosystem.

### New structure

* `/` — main page of the docs. Very important!

* `/ book` (or `/learn`) — section (and a dedicated page) for learning all things Tact and some things TON. Because there's an awesome docs.ton.org resource, many articles and guides, we should reference as much of it as possible, while still remaining Tact-specific and novice-friendly.

* `/language` — section (and a dedicated page) for the vast overview of the language, including:
  * `/grammar` — a dedicated grammar page, #76
  * `/ref` — no change
  * `/libs` — no change
  * `/evolution` — current `/evolution` section should move here, plus a Changelog page (current one has to be replaced by a link to [tact-lang/tact/CHANGELOG.md](https://github.com/tact-lang/tact/blob/main/CHANGELOG.md) as per #77)

* /ecosystem — section (and a dedicated page).

### PR DESCRIPTION
**Pull request by novusnota**
Changed: A lot.
Is it any good? [Yes](https://news.ycombinator.com/item?id=3067434).

Jokes aside, it's awesome.

Introducing:
* New and excellent structure: main - /book - /language - /ecosystem (and **many** related changes described in #79)
* Automatic redirects from old links to new ones (so that no one gets 404'd away!)
* Every section now features links to Tact's: 1. Telegram group, 2. X/Twitter account
* A very quick and sweet tutorial on creating the first contract via the Blueprint on the main page of the docs.
* Page stubs for #54 and #67 in Book→Cheatsheets
* Page stub for #76 in Language→Specification
* ...and many other smaller quality of life changes in the root of the repository.

As a bonus, added internationalization (i18n) support with automatic language detection and included zh (Chinese) as an alternative locale. Note, that no content has been translated to it yet, contributions are very welcome once #80 gets through and enables it :)

As an aside, archived /learn made by @reveloper. This series of articles may later get re-introduced into the /book section.

Closes #79
Closes #77

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
Awesome stuff, indeed!

**Comment by anton-trunov** [comment]
oops, deploy failed: https://github.com/tact-lang/tact-docs/actions/runs/8145321815

**Comment by anton-trunov** [comment]
we should definitely active the "merge only when deploy succeeds" setting for this repo asap

**Comment by novusnota** [comment]
@anton-trunov Definitely. Hold on, I'll send a fix to the deploy in a moment and remove unnecessary items from Nextra docs (/components/icons).

**Pull request merged**
