### PR TITLE
exit codes added

### PR DESCRIPTION
**Pull request by alirezatabatabaeian**
Hi @reveloper @anton-trunov @novusnota 
I've modified the docs as @reveloper said. Now, it's much better.
And made a PR as @novusnota said.
Thanks for it!

### CODE REVIEW

**Comment by reveloper** [comment]
@alirezatabatabaeian please, reaname Tact Phase -> Tact (Compiler) in the exit codes table. 
Also, the column name "TVM Phases" should be common and fit for this. (Exit Code Appears in..) 
Just keep in mind, that the TVM doesn't include the Tact compilation.

**Comment by alirezatabatabaeian** [comment]
@reveloper What is your proposed name instead of "TVM phase"?

**Comment by alirezatabatabaeian** [comment]
@reveloper What is your proposed name instead of "TVM phase"?

**Comment by reveloper** [comment]
Can't advise something specific here, but even "Phase" will be a little better.

**Comment by alirezatabatabaeian** [comment]
@reveloper Done

**Review by anton-trunov — APPROVED** [review]
Thanks so much! This looks great

**Pull request merged**
