### PR TITLE
feat: trailing commas

### LINKED ISSUE #164: Document trailing commas in all comma-separated lists
https://github.com/tact-lang/tact/pull/179 and https://github.com/tact-lang/tact/pull/246

### PR DESCRIPTION
**Pull request by novusnota**
* struct instantiations
* initOf arguments
* init() parameters
* inherited traits via with
* function arguments and parameters

Closes #164

### CODE REVIEW

**Review by anton-trunov — CHANGES_REQUESTED** [review]
Sorry, but most changes look irrelevant to me. We should promote a reasonable code style: using trailing commas only if the parameters, arguments, etc. are placed on separate lines, which usually happens when there is a lot of them or if the current indentation level is too deep. Otherwise trailing commas should not be used.

**Review by anton-trunov — APPROVED** [review]
Looks great!

**Comment by anton-trunov** [comment]
@novusnota I updated the list of checks for the linter issue: https://github.com/tact-lang/tact/issues/295

**Comment by novusnota** [comment]
Awesome!

**Pull request merged**
