### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by howardpen9**
- Adding the Tact-by-example Link
- Add the emoji to highlight the `map` data type

### CODE REVIEW

**Comment by howardpen9** [comment]
@anton-trunov maybe we can suggest some Docs principles, what do you think ~

**Comment by anton-trunov** [comment]
@howardpen9 Can you give an example of what you mean?

**Comment by Cosmodude** [comment]
It also would be great if you could list the supported methods. 
And describe how the map is turned into a func dict

**Comment by howardpen9** [comment]
> It also would be great if you could list the supported methods. And describe how the map is turned into a func dict

Hi @Cosmodude , do you have any example in mind right now? 

because I don't have much issued with that in any scenario. Would be great if you can share some examples. 


Thank you.

**Comment by anton-trunov** [comment]
I would remove unrelated formatting changes (`-` -> `*`), I think it's better to address those as a separate PR if there is need.

And then I think we need some more explanations of the actual additions.

**Comment by Cosmodude** [comment]
The method usage example can be taken from tact by example.
The dictionary creation should be described as specified here: https://github.com/tact-lang/tact/blob/6bc5eb9d9d74c887f870fe4dc9472fed3f5cd8ad/src/abi/map.ts

**Review by Cosmodude — COMMENTED** [review]
I would add the usage of set and get methods for maps at line 63

**Comment by anton-trunov** [comment]
Let me close this a bit stale PR for now. If anyone wants to work on this, please feel free to do so

**Pull request closed without merging**
